/* date */
export const SET_DATE = 'SET_DATE'

/* errors */
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

/* map */
export const SET_MAP_LOCATION = 'SET_MAP_LOCATION'
export const SET_MAP_VIEW = 'SET_MAP_VIEW'

/* route */
export const ADD_ROUTE_WAYPOINT = 'ADD_ROUTE_WAYPOINT'
export const REMOVE_ROUTE_WAYPOINT = 'REMOVE_ROUTE_WAYPOINT'
export const UPDATE_ROUTE_WAYPOINT = 'UPDATE_ROUTE_WAYPOINT'
export const INSERT_ROUTE_WAYPOINT = 'INSERT_ROUTE_WAYPOINT'
export const SET_ROUTE = 'SET_ROUTE'
export const SET_ROUTE_ERROR = 'SET_ROUTE_ERROR'

export const CLEAR_ANALYSIS_MODE = 'CLEAR_ANALYSIS_MODE'
