/* app */
export const SET_ANALYSIS_MODE = 'SET_ANALYSIS_MODE'
export const CLEAR_ANALYSIS = 'CLEAR_ANALYSIS'
export const SET_ANALYSIS_NAME = 'SET_ANALYSIS_NAME'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

/* date */
export const SET_DATE = 'SET_DATE'
export const TOGGLE_TIME_FILTERS = 'TOGGLE_TIME_FILTERS'
export const SET_DAY_FILTER = 'SET_DAY_FILTER'
export const SET_HOUR_FILTER = 'SET_HOUR_FILTER'

/* errors */
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

/* map */
export const SET_MAP_LOCATION = 'SET_MAP_LOCATION'
export const SET_LABEL = 'SET_LABEL'
export const SET_MAP_VIEW = 'SET_MAP_VIEW'

/* route */
export const ADD_ROUTE_WAYPOINT = 'ADD_ROUTE_WAYPOINT'
export const REMOVE_ROUTE_WAYPOINT = 'REMOVE_ROUTE_WAYPOINT'
export const UPDATE_ROUTE_WAYPOINT = 'UPDATE_ROUTE_WAYPOINT'
export const INSERT_ROUTE_WAYPOINT = 'INSERT_ROUTE_WAYPOINT'
export const SET_ROUTE = 'SET_ROUTE'
export const SET_ROUTE_SEGMENTS = 'SET_ROUTE_SEGMENTS'
export const SET_ROUTE_ERROR = 'SET_ROUTE_ERROR'
export const SET_BASELINE_TIME = 'SET_BASELINE_TIME'
export const SET_TRAFFIC_ROUTE_TIME = 'SET_TRAFFIC_ROUTE_TIME'

/* tangram */
export const UPDATE_SCENE = 'UPDATE_SCENE'

/* view */
export const SET_VIEW_BOUNDS = 'SET_VIEW_BOUNDS'
export const CLEAR_VIEW_BOUNDS = 'CLEAR_VIEW_BOUNDS'
export const SET_GEOJSON = 'SET_GEOJSON'
